name: flutter_chat_bar
description: A new Flutter Chat Bar.
version: 0.0.1
homepage: https://nolink.com

publish_to: 'none'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: